-- ========================================
-- SCHEMA
-- ========================================

CREATE SCHEMA IF NOT EXISTS app;

-- ========================================
-- USERS
-- ========================================

CREATE TABLE IF NOT EXISTS app.users (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(150) NOT NULL,
                                         phone VARCHAR(30) NOT NULL UNIQUE,
                                         current_points INTEGER NOT NULL DEFAULT 0 CHECK (current_points >= 0),
                                         created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                         updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ========================================
-- POINT TRANSACTIONS
-- ========================================

CREATE TABLE IF NOT EXISTS app.point_transactions (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      user_id BIGINT NOT NULL,
                                                      transaction_type VARCHAR(50) NOT NULL CHECK (
                                                          transaction_type IN ('EARN', 'SPEND', 'ADJUSTMENT')
                                                          ),
                                                      points_delta INTEGER NOT NULL,
                                                      previous_balance INTEGER NOT NULL CHECK (previous_balance >= 0),
                                                      new_balance INTEGER NOT NULL CHECK (new_balance >= 0),
                                                      created_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                      CONSTRAINT fk_point_transactions_user
                                                          FOREIGN KEY (user_id)
                                                              REFERENCES app.users(id)
                                                              ON DELETE CASCADE,

                                                      CONSTRAINT chk_point_transactions_balance_consistency
                                                          CHECK (new_balance = previous_balance + points_delta)
);

-- ========================================
-- PRIZE CATEGORIES
-- ========================================

CREATE TABLE IF NOT EXISTS app.prize_categories (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    code VARCHAR(50) NOT NULL UNIQUE,
                                                    name VARCHAR(100) NOT NULL
);

-- ========================================
-- PRIZES
-- ========================================

CREATE TABLE IF NOT EXISTS app.prizes (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          category_id BIGINT NOT NULL,
                                          name VARCHAR(150) NOT NULL,
                                          description VARCHAR(255),
                                          points_cost INTEGER NOT NULL CHECK (points_cost >= 0),
                                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                          CONSTRAINT fk_prizes_category
                                              FOREIGN KEY (category_id)
                                                  REFERENCES app.prize_categories(id)
);

-- ========================================
-- PRIZE REDEMPTIONS
-- ========================================

CREATE TABLE IF NOT EXISTS app.prize_redemptions (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     user_id BIGINT NOT NULL,
                                                     prize_id BIGINT NOT NULL,
                                                     point_transaction_id BIGINT NOT NULL UNIQUE,
                                                     points_spent INTEGER NOT NULL CHECK (points_spent > 0),
                                                     redeemed_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                     CONSTRAINT fk_prize_redemptions_user
                                                         FOREIGN KEY (user_id)
                                                             REFERENCES app.users(id)
                                                             ON DELETE CASCADE,

                                                     CONSTRAINT fk_prize_redemptions_prize
                                                         FOREIGN KEY (prize_id)
                                                             REFERENCES app.prizes(id),

                                                     CONSTRAINT fk_prize_redemptions_point_transaction
                                                         FOREIGN KEY (point_transaction_id)
                                                             REFERENCES app.point_transactions(id)
                                                             ON DELETE CASCADE
);

-- ========================================
-- INDEXES
-- ========================================

CREATE INDEX IF NOT EXISTS idx_point_transactions_user
    ON app.point_transactions(user_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_user
    ON app.prize_redemptions(user_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_prize
    ON app.prize_redemptions(prize_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_redeemed_at
    ON app.prize_redemptions(redeemed_at);

-- ========================================
-- SEED DATA - PRIZE CATEGORIES
-- ========================================

INSERT INTO app.prize_categories (code, name) VALUES
                                                  ('VALE', 'Vale'),
                                                  ('DULCE', 'Dulce + Sticker'),
                                                  ('CHICO', 'Premio chico'),
                                                  ('MEDIANO', 'Premio mediano'),
                                                  ('BUENO', 'Premio bueno'),
                                                  ('ALTO', 'Premio alto'),
                                                  ('MAYOR', 'Premio mayor')
ON CONFLICT (code) DO NOTHING;