-- ========================================
-- SCHEMA
-- ========================================

CREATE SCHEMA IF NOT EXISTS app;

-- ========================================
-- USERS
-- ========================================

CREATE TABLE IF NOT EXISTS app.users (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(150) NOT NULL,
                                         phone VARCHAR(30) NOT NULL UNIQUE,
                                         current_points INTEGER NOT NULL DEFAULT 0 CHECK (current_points >= 0),
                                         created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                         updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ========================================
-- POINT TRANSACTIONS
-- ========================================

CREATE TABLE IF NOT EXISTS app.point_transactions (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                      user_id BIGINT NOT NULL,
                                                      transaction_type VARCHAR(50) NOT NULL CHECK (
                                                          transaction_type IN ('EARN', 'SPEND', 'ADJUSTMENT')
                                                          ),
                                                      points_delta INTEGER NOT NULL,
                                                      previous_balance INTEGER NOT NULL CHECK (previous_balance >= 0),
                                                      new_balance INTEGER NOT NULL CHECK (new_balance >= 0),
                                                      created_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                      CONSTRAINT fk_point_transactions_user
                                                          FOREIGN KEY (user_id)
                                                              REFERENCES app.users(id)
                                                              ON DELETE CASCADE,

                                                      CONSTRAINT chk_point_transactions_balance_consistency
                                                          CHECK (new_balance = previous_balance + points_delta)
);

-- ========================================
-- PRIZE CATEGORIES
-- ========================================

CREATE TABLE IF NOT EXISTS app.prize_categories (
                                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    code VARCHAR(50) NOT NULL UNIQUE,
                                                    name VARCHAR(100) NOT NULL
);

-- ========================================
-- PRIZES
-- ========================================

CREATE TABLE IF NOT EXISTS app.prizes (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          category_id BIGINT NOT NULL,
                                          name VARCHAR(150) NOT NULL,
                                          description VARCHAR(255),
                                          points_cost INTEGER NOT NULL CHECK (points_cost >= 0),
                                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                                          cost NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (cost >= 0),
                                          created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                          updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                          CONSTRAINT fk_prizes_category
                                              FOREIGN KEY (category_id)
                                                  REFERENCES app.prize_categories(id)
);

-- ========================================
-- PRIZE REDEMPTIONS
-- ========================================

CREATE TABLE IF NOT EXISTS app.prize_redemptions (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     user_id BIGINT NOT NULL,
                                                     prize_id BIGINT NOT NULL,
                                                     point_transaction_id BIGINT NOT NULL UNIQUE,
                                                     points_spent INTEGER NOT NULL CHECK (points_spent > 0),
                                                     redeemed_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                     CONSTRAINT fk_prize_redemptions_user
                                                         FOREIGN KEY (user_id)
                                                             REFERENCES app.users(id)
                                                             ON DELETE CASCADE,

                                                     CONSTRAINT fk_prize_redemptions_prize
                                                         FOREIGN KEY (prize_id)
                                                             REFERENCES app.prizes(id),

                                                     CONSTRAINT fk_prize_redemptions_point_transaction
                                                         FOREIGN KEY (point_transaction_id)
                                                             REFERENCES app.point_transactions(id)
                                                             ON DELETE CASCADE
);

-- ========================================
-- MACHINE CAMPAIGNS
-- ========================================

CREATE TABLE IF NOT EXISTS app.machine_campaigns (
                                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     name VARCHAR(150) NOT NULL,
                                                     major_prize_id BIGINT NOT NULL,
                                                     status VARCHAR(30) NOT NULL CHECK (
                                                         status IN ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED')
                                                         ),
                                                     base_target_amount NUMERIC(10,2) NOT NULL CHECK (base_target_amount > 0),
                                                     notes TEXT,
                                                     opened_at TIMESTAMP,
                                                     closed_at TIMESTAMP,
                                                     created_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                                     updated_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                     CONSTRAINT fk_machine_campaigns_major_prize
                                                         FOREIGN KEY (major_prize_id)
                                                             REFERENCES app.prizes(id)
);

-- ========================================
-- MACHINE INCOME RECORDS
-- ========================================

CREATE TABLE IF NOT EXISTS app.machine_income_records (
                                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                          campaign_id BIGINT NOT NULL,
                                                          amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
                                                          registered_at TIMESTAMP NOT NULL DEFAULT NOW(),
                                                          notes TEXT,

                                                          CONSTRAINT fk_machine_income_records_campaign
                                                              FOREIGN KEY (campaign_id)
                                                                  REFERENCES app.machine_campaigns(id)
                                                                  ON DELETE CASCADE
);

-- ========================================
-- MACHINE EXPENSE RECORDS
-- ========================================

CREATE TABLE IF NOT EXISTS app.machine_expense_records (
                                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           campaign_id BIGINT NOT NULL,
                                                           prize_id BIGINT NOT NULL,
                                                           quantity INTEGER NOT NULL CHECK (quantity > 0),
                                                           unit_cost NUMERIC(10,2) NOT NULL CHECK (unit_cost >= 0),
                                                           total_cost NUMERIC(10,2) NOT NULL CHECK (total_cost >= 0),
                                                           restocked BOOLEAN NOT NULL DEFAULT FALSE,
                                                           registered_at TIMESTAMP NOT NULL DEFAULT NOW(),

                                                           CONSTRAINT fk_machine_expense_records_campaign
                                                               FOREIGN KEY (campaign_id)
                                                                   REFERENCES app.machine_campaigns(id)
                                                                   ON DELETE CASCADE,

                                                           CONSTRAINT fk_machine_expense_records_prize
                                                               FOREIGN KEY (prize_id)
                                                                   REFERENCES app.prizes(id),

                                                           CONSTRAINT chk_machine_expense_total_cost
                                                               CHECK (total_cost = quantity * unit_cost)
);

-- ========================================
-- INDEXES - LOYALTY
-- ========================================

CREATE INDEX IF NOT EXISTS idx_point_transactions_user
    ON app.point_transactions(user_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_user
    ON app.prize_redemptions(user_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_prize
    ON app.prize_redemptions(prize_id);

CREATE INDEX IF NOT EXISTS idx_prize_redemptions_redeemed_at
    ON app.prize_redemptions(redeemed_at);

-- ========================================
-- INDEXES - MACHINE OPERATIONS
-- ========================================

CREATE INDEX IF NOT EXISTS idx_machine_campaigns_status
    ON app.machine_campaigns(status);

CREATE INDEX IF NOT EXISTS idx_machine_campaigns_major_prize
    ON app.machine_campaigns(major_prize_id);

CREATE INDEX IF NOT EXISTS idx_machine_income_records_campaign
    ON app.machine_income_records(campaign_id);

CREATE INDEX IF NOT EXISTS idx_machine_income_records_registered_at
    ON app.machine_income_records(registered_at);

CREATE INDEX IF NOT EXISTS idx_machine_expense_records_campaign
    ON app.machine_expense_records(campaign_id);

CREATE INDEX IF NOT EXISTS idx_machine_expense_records_prize
    ON app.machine_expense_records(prize_id);

CREATE INDEX IF NOT EXISTS idx_machine_expense_records_registered_at
    ON app.machine_expense_records(registered_at);

CREATE INDEX IF NOT EXISTS idx_machine_expense_records_restocked
    ON app.machine_expense_records(restocked);

-- ========================================
-- SEED DATA - PRIZE CATEGORIES
-- ========================================

INSERT INTO app.prize_categories (code, name) VALUES
                                                  ('VALE', 'Vale'),
                                                  ('DULCE', 'Dulce + Sticker'),
                                                  ('CHICO', 'Premio chico'),
                                                  ('MEDIANO', 'Premio mediano'),
                                                  ('BUENO', 'Premio bueno'),
                                                  ('ALTO', 'Premio alto'),
                                                  ('MAYOR', 'Premio mayor')
ON CONFLICT (code) DO NOTHING;